### ISSUE TITLE
[BUG] Crash when inventory scanning

### ISSUE THREAD

**Issue by KELETU66666** [Wong-Innovations/TC4Research#32]
[16:50:22] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.player.ItemTooltipEvent@29ac5376:
java.lang.NullPointerException: null
	at thecodex6824.thaumicaugmentation.common.research.ScanEntityWithPeacefulFallback.checkThing(ScanEntityWithPeacefulFallback.java:42) ~[ScanEntityWithPeacefulFallback.class:?]
	at thaumcraft.api.research.ScanningManager.isThingStillScannable(ScanningManager.java:91) ~[ScanningManager.class:?]
	at thaumcraft.client.lib.events.RenderEventHandler.oldresearch$shouldRenderAspects(RenderEventHandler.java:1680) ~[RenderEventHandler.class:?]
	at thaumcraft.client.lib.events.RenderEventHandler.handler$zed000$tooltipEventInjection1(RenderEventHandler.java:1625) ~[RenderEventHandler.class:?]
	at thaumcraft.client.lib.events.RenderEventHandler.tooltipEvent(RenderEventHandler.java) ~[RenderEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_11_RenderEventHandler_tooltipEvent_ItemTooltipEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:358) ~[ForgeEventFactory.class:?]
	at net.minecraft.item.ItemStack.getTooltip(ItemStack.java:889) ~[aip.class:?]
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:576) ~[bib.class:?]
	at net.minecraft.client.util.SearchTree.index(SourceFile:49) ~[cgw.class:?]
	at net.minecraft.client.util.SearchTree.add(SourceFile:44) ~[cgw.class:?]
	at java.lang.Iterable.forEach(Iterable.java:75) [?:1.8.0_402]
	at net.minecraft.client.Minecraft.populateSearchTreeManager(Minecraft.java:590) [bib.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.reloadSearchTrees(FMLClientHandler.java:1086) [FMLClientHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.reloadSearchTrees(FMLCommonHandler.java:778) [FMLCommonHandler.class:?]
	at net.minecraftforge.common.ForgeModContainer.mappingChanged(ForgeModContainer.java:589) [ForgeModContainer.class:14.23.5.2859]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_402]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_402]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_402]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_402]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.fireRemapEvent(Loader.java:916) [Loader.class:?]
	at net.minecraftforge.registries.GameData.revertToFrozen(GameData.java:281) [GameData.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.serverStopped(FMLClientHandler.java:673) [FMLClientHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStopped(FMLCommonHandler.java:506) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:587) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_402]
[16:50:22] [Server thread/ERROR] [FML]: Index: 5 Listeners:
[16:50:22] [Server thread/ERROR] [FML]: 0: HIGHEST
[16:50:22] [Server thread/ERROR] [FML]: 1: ASM: class vazkii.botania.client.core.handler.TooltipHandler onTooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[16:50:22] [Server thread/ERROR] [FML]: 2: ASM: com.zeitheron.hammercore.TooltipAPI@3b879b26 tooltipEvt(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[16:50:22] [Server thread/ERROR] [FML]: 3: ASM: org.zeith.thaumicadditions.events.ClientEventReactor@4793b5b8 tooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[16:50:22] [Server thread/ERROR] [FML]: 4: NORMAL
[16:50:22] [Server thread/ERROR] [FML]: 5: ASM: class thaumcraft.client.lib.events.RenderEventHandler tooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[16:50:22] [Server thread/ERROR] [FML]: 6: ASM: class thaumcraft.common.lib.events.PlayerEvents tooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[16:50:22] [Server thread/ERROR] [FML]: 7: ASM: class thecodex6824.thaumicaugmentation.client.event.ClientEventHandler onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[16:50:22] [Server thread/ERROR] [FML]: 8: ASM: class WayofTime.bloodmagic.util.handler.event.ClientHandler onTooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[16:50:22] [Server thread/ERROR] [FML]: 9: ASM: class com.feed_the_beast.ftblib.client.FTBLibClientEventHandler onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[16:50:22] [Server thread/ERROR] [FML]: 10: ASM: class mcp.mobius.waila.handlers.VanillaTooltipHandler tooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[16:50:22] [Server thread/ERROR] [FML]: 11: ASM: class invtweaks.forge.ToolTipEvent tTipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[16:50:22] [Server thread/ERROR] [FML]: 12: ASM: class com.wonginnovations.oldresearch.proxy.ProxyInventoryScanning onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[16:50:22] [Server thread/ERROR] [FML]: 13: ASM: class leppa.planarartifice.main.PlanarArtifice tooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[16:50:22] [Server thread/ERROR] [FML]: 14: ASM: class thaumicperiphery.handler.PhantomInkHandler onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[16:50:22] [Server thread/ERROR] [FML]: 15: ASM: baubles.client.ClientEventHandler@71c7720 tooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[16:50:22] [Server thread/ERROR] [FML]: 16: ASM: class quaternary.botaniatweaks.modules.botania.handler.TooltipHandler handleTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[16:50:22] [Server thread/ERROR] [FML]: 17: ASM: morph.avaritia.handler.AvaritiaEventHandler@413b13a2 onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[16:50:22] [Server thread/ERROR] [FML]: 18: ASM: class fr.wind_blade.isorropia.client.libs.RenderEventHandler onToolTip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[16:50:22] [Server thread/ERROR] [FML]: 19: ASM: keletu.forbiddenmagicre.event.LivingEvent@67338d28 tooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[16:50:22] [Server thread/ERROR] [FML]: 20: ASM: alexiy.thaumic.addon.ClientEvents@39e137b1 itemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[16:50:22] [Server thread/ERROR] [FML]: 21: ASM: com.focamacho.dupefixproject.event.ThaumcraftEvents@335108a9 tooltipFix(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[16:50:22] [Server thread/ERROR] [FML]: 22: ASM: squeek.wailaharvestability.TooltipHandler@14cac35d tooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[16:50:22] [Server thread/ERROR] [FML]: 23: LOW
[16:50:22] [Server thread/ERROR] [FML]: 24: ASM: crafttweaker.mc1120.events.ClientEventHandler@1ed3e93b onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[16:50:22] [Server thread/ERROR] [FML]: 25: LOWEST
[16:50:22] [Server thread/ERROR] [FML]: 26: ASM: class com.buuz135.thaumicjei.gui.AspectTooltipHandler tooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
[16:50:22] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Minecraft Forge (forge)
[16:50:22] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: Caused by: java.lang.NullPointerException
[16:50:22] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at thecodex6824.thaumicaugmentation.common.research.ScanEntityWithPeacefulFallback.checkThing(ScanEntityWithPeacefulFallback.java:42)
[16:50:22] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at thaumcraft.api.research.ScanningManager.isThingStillScannable(ScanningManager.java:91)
[16:50:22] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at thaumcraft.client.lib.events.RenderEventHandler.oldresearch$shouldRenderAspects(RenderEventHandler.java:1680)
[16:50:22] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at thaumcraft.client.lib.events.RenderEventHandler.handler$zed000$tooltipEventInjection1(RenderEventHandler.java:1625)
[16:50:22] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at thaumcraft.client.lib.events.RenderEventHandler.tooltipEvent(RenderEventHandler.java)
[16:50:22] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_11_RenderEventHandler_tooltipEvent_ItemTooltipEvent.invoke(.dynamic)
[16:50:22] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[16:50:22] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
[16:50:22] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:358)
[16:50:22] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraft.item.ItemStack.getTooltip(ItemStack.java:889)
[16:50:22] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:576)
[16:50:22] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraft.client.util.SearchTree.index(SourceFile:49)
[16:50:22] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraft.client.util.SearchTree.add(SourceFile:44)
[16:50:22] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at java.lang.Iterable.forEach(Iterable.java:75)
[16:50:22] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraft.client.Minecraft.populateSearchTreeManager(Minecraft.java:590)
[16:50:22] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraftforge.fml.client.FMLClientHandler.reloadSearchTrees(FMLClientHandler.java:1086)
[16:50:22] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraftforge.fml.common.FMLCommonHandler.reloadSearchTrees(FMLCommonHandler.java:778)
[16:50:22] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraftforge.common.ForgeModContainer.mappingChanged(ForgeModContainer.java:589)
[16:50:22] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:50:22] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[16:50:22] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:50:22] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[16:50:22] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[16:50:22] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[16:50:22] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[16:50:22] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[16:50:22] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[16:50:22] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[16:50:22] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[16:50:22] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
[16:50:22] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
[16:50:22] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraftforge.fml.common.Loader.fireRemapEvent(Loader.java:916)
[16:50:22] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraftforge.registries.GameData.revertToFrozen(GameData.java:281)
[16:50:22] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraftforge.fml.client.FMLClientHandler.serverStopped(FMLClientHandler.java:673)
[16:50:22] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStopped(FMLCommonHandler.java:506)
[16:50:22] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:587)
[16:50:22] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at java.lang.Thread.run(Thread.java:750)

**Comment by KELETU66666** [comment]
![image](https://github.com/Wong-Innovations/TC4Research/assets/92129388/3aa0a74a-37e3-4dbd-92fd-97d0132a0af1)
